/**
 * Real-world vocabularies. Structure is synthetic, but jurisdictions, legal forms, registered-agent
 * conventions and name pools are drawn from reality so the graph reads as plausible rather than
 * obviously generated. Secrecy scores are indicative, in the spirit of the Financial Secrecy Index.
 */

export interface JurisdictionSeed {
  code: string;
  name: string;
  secrecyScore: number;
  /** Weight for shell/holding companies — secrecy jurisdictions dominate here. */
  shellWeight: number;
  /** Weight for real operating companies. */
  operatingWeight: number;
  legalForms: readonly string[];
}

export const JURISDICTIONS: readonly JurisdictionSeed[] = [
  {
    code: 'VG',
    name: 'British Virgin Islands',
    secrecyScore: 8.9,
    shellWeight: 22,
    operatingWeight: 1,
    legalForms: ['Ltd', 'Corp'],
  },
  {
    code: 'PA',
    name: 'Panama',
    secrecyScore: 7.2,
    shellWeight: 16,
    operatingWeight: 1,
    legalForms: ['SA', 'Inc'],
  },
  {
    code: 'KY',
    name: 'Cayman Islands',
    secrecyScore: 8.5,
    shellWeight: 15,
    operatingWeight: 1,
    legalForms: ['Ltd', 'Exempted Company'],
  },
  {
    code: 'CY',
    name: 'Cyprus',
    secrecyScore: 6.4,
    shellWeight: 12,
    operatingWeight: 3,
    legalForms: ['Ltd', 'Holdings Ltd'],
  },
  {
    code: 'SC',
    name: 'Seychelles',
    secrecyScore: 7.5,
    shellWeight: 10,
    operatingWeight: 1,
    legalForms: ['IBC', 'Ltd'],
  },
  {
    code: 'BZ',
    name: 'Belize',
    secrecyScore: 7.6,
    shellWeight: 8,
    operatingWeight: 1,
    legalForms: ['IBC', 'Ltd'],
  },
  {
    code: 'MT',
    name: 'Malta',
    secrecyScore: 6.0,
    shellWeight: 7,
    operatingWeight: 3,
    legalForms: ['Ltd', 'plc'],
  },
  {
    code: 'LU',
    name: 'Luxembourg',
    secrecyScore: 5.5,
    shellWeight: 9,
    operatingWeight: 4,
    legalForms: ['S.a r.l.', 'S.A.'],
  },
  {
    code: 'NL',
    name: 'Netherlands',
    secrecyScore: 4.9,
    shellWeight: 8,
    operatingWeight: 8,
    legalForms: ['B.V.', 'N.V.'],
  },
  {
    code: 'AE',
    name: 'United Arab Emirates',
    secrecyScore: 7.8,
    shellWeight: 9,
    operatingWeight: 5,
    legalForms: ['FZE', 'LLC'],
  },
  {
    code: 'SG',
    name: 'Singapore',
    secrecyScore: 6.7,
    shellWeight: 6,
    operatingWeight: 7,
    legalForms: ['Pte Ltd'],
  },
  {
    code: 'HK',
    name: 'Hong Kong',
    secrecyScore: 6.6,
    shellWeight: 8,
    operatingWeight: 6,
    legalForms: ['Ltd'],
  },
  {
    code: 'CH',
    name: 'Switzerland',
    secrecyScore: 7.0,
    shellWeight: 5,
    operatingWeight: 6,
    legalForms: ['AG', 'SA'],
  },
  {
    code: 'JE',
    name: 'Jersey',
    secrecyScore: 6.6,
    shellWeight: 6,
    operatingWeight: 1,
    legalForms: ['Ltd'],
  },
  {
    code: 'GG',
    name: 'Guernsey',
    secrecyScore: 7.1,
    shellWeight: 4,
    operatingWeight: 1,
    legalForms: ['Ltd'],
  },
  {
    code: 'IM',
    name: 'Isle of Man',
    secrecyScore: 6.4,
    shellWeight: 4,
    operatingWeight: 1,
    legalForms: ['Ltd'],
  },
  {
    code: 'LI',
    name: 'Liechtenstein',
    secrecyScore: 7.4,
    shellWeight: 4,
    operatingWeight: 1,
    legalForms: ['AG', 'Anstalt'],
  },
  {
    code: 'GB',
    name: 'United Kingdom',
    secrecyScore: 4.6,
    shellWeight: 5,
    operatingWeight: 20,
    legalForms: ['Ltd', 'plc', 'LLP'],
  },
  {
    code: 'IE',
    name: 'Ireland',
    secrecyScore: 4.7,
    shellWeight: 4,
    operatingWeight: 6,
    legalForms: ['Ltd', 'DAC'],
  },
  {
    code: 'US',
    name: 'United States',
    secrecyScore: 6.7,
    shellWeight: 6,
    operatingWeight: 18,
    legalForms: ['LLC', 'Inc', 'Corp'],
  },
  {
    code: 'DE',
    name: 'Germany',
    secrecyScore: 5.2,
    shellWeight: 2,
    operatingWeight: 12,
    legalForms: ['GmbH', 'AG'],
  },
  {
    code: 'FR',
    name: 'France',
    secrecyScore: 5.1,
    shellWeight: 2,
    operatingWeight: 10,
    legalForms: ['SARL', 'SAS'],
  },
  {
    code: 'ES',
    name: 'Spain',
    secrecyScore: 5.0,
    shellWeight: 2,
    operatingWeight: 8,
    legalForms: ['S.L.', 'S.A.'],
  },
  {
    code: 'PL',
    name: 'Poland',
    secrecyScore: 5.0,
    shellWeight: 1,
    operatingWeight: 7,
    legalForms: ['Sp. z o.o.'],
  },
  {
    code: 'TR',
    name: 'Turkiye',
    secrecyScore: 5.9,
    shellWeight: 2,
    operatingWeight: 6,
    legalForms: ['A.S.', 'Ltd Sti'],
  },
  {
    code: 'ID',
    name: 'Indonesia',
    secrecyScore: 5.7,
    shellWeight: 1,
    operatingWeight: 7,
    legalForms: ['PT', 'PT Tbk'],
  },
] as const;

/** Trusts and foundations are a legal form, not a separate label — see CONTEXT.md. */
export const SPECIAL_LEGAL_FORMS = ['Trust', 'Foundation', 'Private Foundation'] as const;

export const COMPANY_PREFIXES = [
  'Arcadia',
  'Meridian',
  'Northwind',
  'Pelagic',
  'Vantage',
  'Halcyon',
  'Cobalt',
  'Bramble',
  'Sable',
  'Kestrel',
  'Orinoco',
  'Larkspur',
  'Ironwood',
  'Cascadia',
  'Verdant',
  'Solstice',
  'Tamarind',
  'Quarry',
  'Lattice',
  'Perihelion',
  'Basalt',
  'Marlin',
  'Juniper',
  'Anvil',
  'Cinnabar',
  'Driftwood',
  'Fenwick',
  'Gossamer',
  'Hollis',
  'Indigo',
  'Jetty',
  'Kilnstone',
  'Lodestar',
  'Mistral',
  'Nightjar',
  'Obsidian',
  'Pallas',
  'Quicksilver',
  'Rookery',
  'Selkirk',
  'Thornbury',
  'Umber',
  'Vesper',
  'Wexford',
  'Yarrow',
  'Zephyr',
  'Aldgate',
  'Bellweather',
  'Carrick',
  'Dunmore',
] as const;

export const COMPANY_SUFFIX_WORDS = [
  'Holdings',
  'Capital',
  'Partners',
  'Ventures',
  'Investments',
  'Group',
  'Trading',
  'Resources',
  'Logistics',
  'Maritime',
  'Infrastructure',
  'Energy',
  'Property',
  'Assets',
  'Equities',
  'Management',
  'Industries',
  'Global',
  'International',
  'Nominees',
] as const;

export const GIVEN_NAMES = [
  'Konstantin',
  'Elena',
  'Viktor',
  'Marta',
  'Dmitri',
  'Sofia',
  'Andrei',
  'Clara',
  'Tomas',
  'Ingrid',
  'Rafael',
  'Nadia',
  'Piotr',
  'Amara',
  'Hassan',
  'Leila',
  'Mateo',
  'Yusuf',
  'Anneke',
  'Bogdan',
  'Camille',
  'Dario',
  'Esme',
  'Farid',
  'Greta',
  'Hugo',
  'Iris',
  'Janek',
  'Katarina',
  'Lars',
  'Mirela',
  'Nikolai',
  'Olena',
  'Pavel',
  'Rania',
  'Stefan',
  'Tara',
  'Umar',
  'Vera',
  'Wojciech',
  'Xenia',
  'Yannis',
  'Zofia',
  'Adnan',
  'Beatriz',
  'Cyril',
  'Dalia',
  'Emil',
  'Freya',
  'Goran',
] as const;

export const FAMILY_NAMES = [
  'Belov',
  'Marchetti',
  'Anand',
  'Voss',
  'Kowalski',
  'Halloran',
  'Nakamura',
  'Okonkwo',
  'Petrov',
  'Rahman',
  'Silva',
  'Toledano',
  'Ustinov',
  'Varga',
  'Weiss',
  'Yilmaz',
  'Zielinski',
  'Andersen',
  'Bergman',
  'Costa',
  'Dvorak',
  'Eriksen',
  'Fontaine',
  'Grigoryan',
  'Haddad',
  'Ivanova',
  'Jansen',
  'Kaminski',
  'Lindqvist',
  'Moreau',
  'Novak',
  'Ortega',
  'Pavlenko',
  'Quintero',
  'Rossi',
  'Sorensen',
  'Tanaka',
  'Ulrich',
  'Vasquez',
  'Wallenberg',
  'Xiao',
  'Yakovlev',
  'Zhelev',
  'Aliyev',
  'Brandt',
  'Chernov',
  'Dimitrov',
  'Escobar',
  'Falkner',
  'Gruber',
] as const;

export interface AddressSeed {
  line1: string;
  city: string;
  countryCode: string;
  /** Mass-registration addresses host hundreds of companies — the classic weak signal. */
  massRegistration: boolean;
}

export const NOTABLE_ADDRESSES: readonly AddressSeed[] = [
  { line1: 'PO Box 3151, Road Town', city: 'Tortola', countryCode: 'VG', massRegistration: true },
  {
    line1: 'Craigmuir Chambers, PO Box 71',
    city: 'Road Town',
    countryCode: 'VG',
    massRegistration: true,
  },
  {
    line1: 'Ugland House, South Church Street',
    city: 'George Town',
    countryCode: 'KY',
    massRegistration: true,
  },
  {
    line1: 'Arango-Orillac Building, 54th Street',
    city: 'Panama City',
    countryCode: 'PA',
    massRegistration: true,
  },
  {
    line1: 'Suite 305, Griffith Corporate Centre',
    city: 'Beachmont',
    countryCode: 'BZ',
    massRegistration: true,
  },
  {
    line1: 'Global Gateway 8, Rue de la Perle',
    city: 'Providence',
    countryCode: 'SC',
    massRegistration: true,
  },
  {
    line1: '2 Themistokli Dervi, Julia House',
    city: 'Nicosia',
    countryCode: 'CY',
    massRegistration: true,
  },
] as const;

export const STREET_NAMES = [
  'Harley Street',
  'Kingsway',
  'Prinsengracht',
  'Bahnhofstrasse',
  'Rue du Rhone',
  'Wall Street',
  'Marina Boulevard',
  'Sheikh Zayed Road',
  'Connaught Road',
  'Grand Rue',
  'Jalan Sudirman',
  'Nowy Swiat',
  'Gran Via',
  'Karntner Strasse',
  'Vaci utca',
] as const;

export const CITIES: readonly (readonly [string, string])[] = [
  ['London', 'GB'],
  ['Amsterdam', 'NL'],
  ['Zurich', 'CH'],
  ['Geneva', 'CH'],
  ['New York', 'US'],
  ['Singapore', 'SG'],
  ['Dubai', 'AE'],
  ['Hong Kong', 'HK'],
  ['Luxembourg', 'LU'],
  ['Valletta', 'MT'],
  ['Jakarta', 'ID'],
  ['Warsaw', 'PL'],
  ['Madrid', 'ES'],
  ['Berlin', 'DE'],
  ['Paris', 'FR'],
  ['Istanbul', 'TR'],
  ['Dublin', 'IE'],
  ['Douglas', 'IM'],
  ['St Helier', 'JE'],
  ['Vaduz', 'LI'],
] as const;

export const INTERMEDIARY_NAMES = [
  'Tortola Corporate Services',
  'Meridian Trust Company',
  'Ugland Fiduciaries',
  'Arango Legal Partners',
  'Griffith Nominees',
  'Providence Company Formations',
  'Nicosia Corporate Advisers',
  'Sovereign Trust International',
  'Blackwater Fiduciary Group',
  'Cardinal Registrars',
  'Equinox Corporate Agents',
  'Lighthouse Trustees',
  'Pinnacle Company Secretaries',
  'Northgate Fiduciary',
  'Silverline Trust Services',
  'Anchor Point Registrars',
  'Bluewater Corporate Management',
  'Crestline Nominee Services',
] as const;

export const INTERMEDIARY_TYPES = [
  'Registered Agent',
  'Law Firm',
  'Trust Company',
  'Corporate Services Provider',
] as const;

export const WATCHLISTS = [
  { id: 'W-OFAC', name: 'OFAC SDN', authority: 'US Department of the Treasury' },
  { id: 'W-EU', name: 'EU Consolidated Sanctions', authority: 'European Union' },
  { id: 'W-OFSI', name: 'UK OFSI Consolidated List', authority: 'HM Treasury' },
] as const;

export const SANCTIONS_PROGRAMS = [
  'RUSSIA-EO14024',
  'GLOMAG',
  'SDGT',
  'CYBER2',
  'UKRAINE-EO13662',
  'IRAN-EO13846',
] as const;

export const OFFICER_ROLES = [
  'Director',
  'Secretary',
  'Shareholder of record',
  'Treasurer',
  'Managing Director',
] as const;
